version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/app:ro
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=password123
      - DATABASE_NAME=baby
      - DATABASE_USERNAME=postgres
      - SECRET_KEY=c242d3545437d99cb0692e19a3bffac5c4f8b2d114b0244fb8d546b9054dcc7e
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=baby

    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
